release.database.user=
release.database.password=
release.database.host=
release.database.dbName=
release.database.port=

curator.hostURL=
curator.username=
curator.password=

personId=
releaseNumber=
testMode=
